name: Deploy Application

on:
  push:
    branches:
      -master

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: windows
    steps:
      - uses: actions/checkout@v2

      -name: Compile CSS Javascript
        run:
          npm install
          npm run prod